version: '3'
services:
  proxy:
    image: nginx
    restart: always
    container_name: reverse_proxy
    ports:
      - "443:80"
    volumes: 
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    
